# Generated by Django 4.0.1 on 2022-02-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_alter_webpage_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='User2',
        ),
    ]
